# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Firebase Hosting CD
env: 
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

on:
  push:
    branches: [ master ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache NPM
      uses: actions/cache@v1.1.2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - run: npm run deploy:staging --if-present
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: DistFiles
        path: dist
    
      env:
        CI: true
